name: Build Clothoids Wrapper
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        choco install eigen -y --version 3.4.0
        choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Build pybind11
      shell: pwsh
      run: |
        cd pyclothoids/Submodules/pybind11
        mkdir build
        cd build
        cmake .. -DPYBIND11_TEST=OFF
        cmake --build . --config Release
        cmake --install . --prefix install_dir

    - name: Build Python Wrapper
      shell: pwsh
      run: |
        cd pyclothoids/src_py
        mkdir build
        cd build
        cmake .. `
          -Dpybind11_DIR="../Submodules/pybind11/build/install_dir/share/cmake/pybind11" `
          -DEigen3_DIR="C:/ProgramData/chocolatey/lib/eigen/tools/include/eigen3"
        cmake --build . --config Release

    - uses: actions/upload-artifact@v4
      with:
        name: G2lib
        path: pyclothoids/src_py/build/Release/G2lib.*.pyd
