name: Build Clothoids Wrapper
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        choco install eigen -y --version 3.4.0
        choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Configure and Build
      shell: pwsh
      run: |
        mkdir build
        cd build
        cmake .. `
          -Dpybind11_DIR="Submodules/pybind11" `
          -DEigen3_DIR="C:/ProgramData/chocolatey/lib/eigen/tools/include/eigen3"
        cmake --build . --config Release --target G2lib

    - uses: actions/upload-artifact@v4
      with:
        name: G2lib
        path: build/src_py/Release/G2lib.*.pyd
